language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
- sudo add-apt-repository ppa:beineri/opt-qt594-trusty -y
- sudo apt-get update -qq

install:
- sudo apt-get -y install qt59base
- source /opt/qt*/bin/qt*-env.sh

jobs:
  include:
  - stage: build
    script:
    - mkdir build
    - cd build
    - cmake ..
    - make VERBOSE=1
  - stage: test
    script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TESTS=ON
    - make
    - xvfb-run make test CTEST_OUTPUT_ON_FAILURE=1
